package com.dailyapps.common.utils

object NavRoute {
    const val loginScreen = "loginScreen"
    const val registerScreen = "registerScreen"
    const val homeScreen = "homeScreen"
    const val absentScreen = "absentScreen"
    const val listExamScreen = "listExamScreen"
    const val detailExamScreen = "detailExamScreen"
    const val tokeExamScreen = "tokenExamScreen"
    const val scoreScreen = "scoreScreen"
    const val scoreDetailScreen = "scoreDetailScreen"
    const val noteScreen = "noteScreen"
    const val testExamScreen = "testExamScreen"
    const val profileScreen = "profileScreen"
    const val profileDetailScreen = "profileDetailScreen"
    const val changePasswordScreen = "changePasswordScreen"
    const val visiMisiScreen = "visiMisiScreen"
    const val observationScreen = "observationScreen"
    const val activityPlanScreen = "activityPlanScreen"
    const val observationDetailScreen = "observationDetailScreen"
    const val activityPlanDetailScreen = "activityPlanDetailScreen"
    const val formObservationScreen = "formObservationScreen"
    const val formReportScreen = "formReportScreen"
    const val formActivityPlanScreen = "formActivityPlanScreen"
    const val reportScreen = "reportScreen"
    const val formMemoScreen = "formMemoScreen"
    const val memoDetailScreen = "memo_detail_screen"
    const val memoListScreen = "memoListScreen"
    const val selfReflectionScreen = "selfReflectionScreen"
    const val selfReflectionDetailScreen = "selfReflectionDetailScreen"
    const val selfReflectionFormScreen = "selfReflectionFormScreen"

}